### ISSUE TITLE
First-pass review

### ISSUE THREAD

**Issue by dwinston** [JPalakapilly/optimanage#1]
Overall, a very nice start! I appreciate you seeking feedback at an early stage. Some items to address:

- [x] Add README.md with example usage

    To clarify the intent of each class and its methods, and to clarify how objects of each class interact, please draft a `README.md` file in the root directory of this repository that walks through a simple example usage scenario. This will help expose what seems off.

- [x] Flesh out class/method docstrings a bit

    To clarify the types and meanings of inputs and outputs, use ["Google style" docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). At a minimum, you want a one-line summary, an `Args:` section if there are input paramers, and a `Returns:` section if there is a return value. Also, each class should have an `__init__` method.

- [x] (minor) Follow PEP8 style conventions

    Class names should be CamelCased. Whatever text editor you use, see about installing a "python linter" plugin that will automatically point out little things like this for you.

**Comment by JPalakapilly** [comment]
I've drafted a `README.md` and updated classes according to your suggestions. Let me know what you think.

**Comment by dwinston** [comment]
Very nice. See #2
