### ISSUE TITLE
Second-pass review

### ISSUE THREAD

**Issue by dwinston** [JPalakapilly/optimanage#2]
Great job! Some ideas:

- `Objective.return_scores` should return a mapping from candidate id to score. The dispatcher is responsible for setting workflow priorities based on collecting these candidate scores from registered objectives and asking these objectives for their workflow dependencies.
- `Objective.train_model` seems redundant. An objective can simply ask its model to `self.train()`.
- `Model.validation` should be renamed `Model.validate` to be consistent with the active verbs used for its other methods.
- For `Model.predict`, I anticipate we will benefit from having a extensible set of input and response types. For example, we may have a classification response type (encapsulating a discrete value) and a regression response type (encapsulating a float). Or, equivalently, we will have `Model` subclasses that represent the use of specific (input, response) types.
- `Dispatcher.update` appears to be responsible for prompting its registered objectives to retrain their models if needed. Thus, a dispatcher needs to serialize, or at least hash, the list of entry/material ids with computed values available to that objective for model training. A dataset may have changed, but perhaps it has only changed in a way significant to some objectives: other objectives may not require re-training their models. Please include consideration of this, e.g. an instance variable.
- Syntax for argument and return types: See the Python [typing](https://docs.python.org/3.6/library/typing.html) module. For example, rather than `list(string)`, `typing.List[string]` (or just `List[string]`) is a good convention for us to follow. I personally do not feel we need to write full type signatures -- I think the docstring format is fine, and is widely supported for automatic documentation, whereas type signatures are a very new thing in Python.

Once you have addressed the above, I think we'll be ready to try to implement some toy examples of each class and write unit tests for them.

**Comment by JPalakapilly** [comment]
Agreed with all these suggestions. Latest code should reflect all changes.

**Comment by dwinston** [comment]
Okay, thanks.
